FROM bellsoft/liberica-openjdk-alpine:11

COPY ./src /src

RUN mkdir ./out

RUN javac -sourcepath ./src -d /src/out /src/Homework_1/src/simple/Main.java /src/Homework_1/regular/Decorator.java /src/Homework_1/src/regular/OtherClass.java

CMD java -classpath ./out Homework_1.src.simple.Main